version: '3.4'

services:
  reactapp-js:
    build:
      context: react-app
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:80

# docker-compose -f "workshop/shopathome/docker-compose.yml" up -d --build