# docker-compose -f "workshop/shopathome/docker-compose.yml" up -d --build
version: '3.4'

services:
  reactapp-js:
    build:
      context: react-app
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:80

  angular-js:
    build:
      context: angular-app
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:80

  vue-js:
    build:
      context: vue-app
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3002:80
